### ISSUE TITLE
Javascript file size limited to 10kB

### ISSUE THREAD

**Issue by plagree** [iskurbanov/theme-app-extension-react#25]
@iskurbanov Nice project!

When building the app, given that Shopify javascript file size limitation is 10kB, this leaves very limited options in terms of dependencies. Especially with React size. Did you manage to include react as an external dependency (not include it in the build but making it available to the theme app?)

**Comment by javl** [comment]
Was wondering the same. I'd love to be able to use React as it makes things a lot easier than having to use vanilla JS, but even without any special imports the filesize easily becomes ~100kB which is 10x the maximum allowed size. This will work during development (you'll just get a warning) but won't be allowed in the store. So very curious to hear how/if you managed to keep the size below 10kb. 
The only way I can think of is by having you extension load in some external JS which can be over the limit, but I don't think this will be allowed in the store either (nor is it good practice).

**Comment by plagree** [comment]
@javl Actually, I realized that the 10kB is not a hard limit but only a suggestion. Just use the `--force` flag to push the extension.
So you can use react or even better preact to keep things as small as possible but 10kB won't be a blocker ;)

**Comment by javl** [comment]
I wonder if you could still get the 'made for Shopify' label if your app doesn't abide to the size rules.
