### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by iffikhan30** [iskurbanov/theme-app-extension-react#39]
I run the command npm run dev it's show me error 

`To investigate the issue, examine this stack trace:                                          │
│    at pollTunnelStatus [as _onTimeout] (@shopify/app/src/cli/services/dev/urls.ts:107)        │
│      if (result.status === 'error') return reject(new BugError(result.message,                │
│      result.tryMessage))                                                                      │
│    at listOnTimeout (node:internal/timers:569)                                                │
│    at processTimers (node:internal/timers:512)  `

After i search google, the issue is cloudflare, Then i install ngrok, I connect my project to tunnel ngraok, the issue is same.

**Comment by iskurbanov** [comment]
Haven’t seen this one before unfortunately. Make sure you’re specifying the correct port on ngrok/cloudflare. 

Are you on Mac or windows?

**Comment by iffikhan30** [comment]
Yes, i am using the right command, i use this prevouse my remix application its work fine.

i am using windows
